<?php

declare(strict_types=1);

namespace App\Builder\ValueObject\Project;

use App\ValueObject\File;
use Symfony\Component\Yaml\Yaml;

/**
 * @author Laurent Bassin <laurent@bassin.info>
 */
class DockerCompose
{
    private $version = '3.6';
    private $services = [];

    public function addService(Service $container)
    {
        $this->services[] = $container;
    }

    public function toArray(): array
    {
        $services = [];
        /** @var Service $service */
        foreach ($this->services as $service) {
            $services[$service->getId()] = $service->toArray();
        }

        return [
            'version' => $this->version,
            'services' => $services,
        ];
    }

    public function __toString(): string
    {
        $header = "# Generated by Okty.io";
        $output = YAML::dump($this->toArray(), 5);

        return sprintf("%s%s%s", $header, PHP_EOL, $output);
    }

    public function getAsFile(): File
    {
        $content = $this->__toString();

        return new File('docker-compose.yaml', $content);
    }
}
